### ISSUE TITLE
Constructor

### ISSUE THREAD

**Issue by manatech** [murka/outlinevpn-api#5]
Hi. Seems that there is a problem with the library: I got this error:

```
const outlinevpn = new OutlineVPN({
                   ^

TypeError: OutlineVPN is not a constructor
```

**Comment by flathead** [comment]
The same problem in Node.js application.

**Comment by flathead** [comment]
If you encounter an issue in **Node.js**, you need to import the library differently:

`const OutlineVPN = require("outlinevpn-api").default;`

This way of importing solves the "is not a constructor" issue.

**Comment by murka** [comment]
@manatech @flathead, thanks you for your feedbacks!

You can install v2.1.0, and use:
```ts
import { OutlineVPN } from 'outlinevpn-api'
```
