### ISSUE TITLE
Is there any way to gate data usage by the user

### ISSUE THREAD

**Issue by manatech** [murka/outlinevpn-api#6]
Hey. Thank you for this great API library

But It seems that there is no way to get data usage by a user. Or may be I'm wrong.

**Comment by murka** [comment]
Hi, @manatech!

You can get data usage all of users and filter it:

```ts

async function main() {
  try {
   const { bytesTransferredByUserId } = await outline.getDataUsage()
   const userId = "0"
   console.log(`user with ${userId} transfer ${bytesTransferredByUserId[userId]} byte of data`)
  } catch (error) {
    console.error(error)
  } 
}
```

**Comment by murka** [comment]
I can provide new method on outline-server for get data usage of specific userId, if it is important method.

**Comment by murka** [comment]
@manatech, you can install 2.2.0 version of package, and use:
```ts
outline.getDataUserUsage(userId)
```

**Comment by manatech** [comment]
@murka Sure. Thank you
